version: 2
jobs:
  build:
    working_directory: ~/coravel
    docker: 
      - image: microsoft/dotnet:3.1-sdk
    steps:
      - checkout
      - run: 'dotnet build ./Src/All.sln'
      - run: 'dotnet test ./Src/UnitTests/MailerUnitTests/MailerUnitTests.csproj'
      - run: 'dotnet test ./Src/UnitTests/CoravelUnitTests/CoravelUnitTests.csproj'
      - run: 'dotnet test ./Src/IntegrationTests/Tests/Tests.csproj'
