version: 2
jobs:
  build:
    working_directory: ~/coravel
    docker: 
      - image: microsoft/dotnet:2.2-sdk
    steps:
      - checkout
      - run: 'dotnet test ./Src/UnitTests/UnitTests.csproj'
      - run: 'dotnet test ./Src/IntegrationTests/Tests/Tests.csproj'